language: javascript


stages:
  - Test
  - Release

jobs:
  include:
    - stage: Test
      language: node_js
      node_js:
        - "8"
      install:
        - npm install
        - npm install -E openzeppelin-solidity
      before_script:
        - echo "//registry.npmjs.org/:_authToken=\${NPM_TOKEN}" > .npmrc
        - npm install -g ganache-cli
        - npm run start &
        - npm install -g codecov
      script:
        - truffle test
        - npm run coverage
      after_script:
        - codecov

    - stage: Release
      provider: script
      node_js:
        - "8"
      before_install:
        - npm install -g npx
        - echo "//registry.npmjs.org/:_authToken=\${NPM_TOKEN}" > .npmrc
      script:
        - npx semantic-release